# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release',
            field=models.ForeignKey(blank=True, help_text='Latest stable release', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_stable', to='release.Release'),
        ),
    ]
