# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('wiki', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('discussion', '0002_auto_20170607_1530'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_auto_20170607_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Members in the team', related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Select a photo to be used as an icon. You can only select from photos you have already uploaded to the gallery.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
        ),
        migrations.AddField(
            model_name='team',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tags for the project', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='team',
            name='threads',
            field=models.ManyToManyField(help_text='Threads related to this', to='discussion.Thread'),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(help_text='Manager of the team', on_delete=django.db.models.deletion.CASCADE, related_name='managed_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='wikisite',
            field=models.ForeignKey(blank=True, help_text='Project wiki', null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.WikiSite'),
        ),
    ]
