# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openlab.counted.models
import openlab.gallery.models
import s3uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of items ever added')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, help_text='Title of this link', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A longer description, or notes about this link', max_length=2048)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('flickr', 'Flickr')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', openlab.counted.models.AutoScopedNumberField(db_index=True, editable=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('path', models.FileField(help_text='Path to raw photo', upload_to=openlab.gallery.models.file_path_builder)),
                ('title', models.CharField(blank=True, help_text='Title of this photo', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A longer description, or notes about this photo', max_length=2048)),
                ('is_uploaded', models.BooleanField(default=False, help_text='Has the file successfully finished uploading?')),
                ('gallery', models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Gallery')),
            ],
            bases=(models.Model, s3uploader.models.GenericUploadableMixin),
        ),
    ]
