# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openlab.counted.models
import openlab.gallery.models
import openlab.prequeue.models
import s3uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of items ever added')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image_thumb', models.ImageField(blank=True, help_text='Image thumb', upload_to=openlab.prequeue.models.thumb_builder)),
                ('preview_image', models.ImageField(blank=True, help_text='Full size image preview', upload_to=openlab.prequeue.models.image_builder)),
                ('preview_file', models.FileField(blank=True, help_text='File in alternative format for preview', upload_to=openlab.prequeue.models.preview_builder)),
                ('preview_html', models.TextField(blank=True, help_text='Text for a plug-in based preview of the file')),
                ('preview_tried', models.BooleanField(db_index=True, default=False, help_text='Have we yet tried encoding a preview for this file? (ie or is it still on the queue)')),
                ('preview_tried_date', models.DateField(blank=True, help_text='When did we last try encoding a preview for this file? (Useful for if we start supporting new preview formats.)', null=True)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, help_text='Title of this link', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A longer description, or notes about this link', max_length=2048)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('flickr', 'Flickr')], max_length=16)),
                ('gallery', models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='medialinks', to='gallery.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image_thumb', models.ImageField(blank=True, help_text='Image thumb', upload_to=openlab.prequeue.models.thumb_builder)),
                ('preview_image', models.ImageField(blank=True, help_text='Full size image preview', upload_to=openlab.prequeue.models.image_builder)),
                ('preview_file', models.FileField(blank=True, help_text='File in alternative format for preview', upload_to=openlab.prequeue.models.preview_builder)),
                ('preview_html', models.TextField(blank=True, help_text='Text for a plug-in based preview of the file')),
                ('preview_tried', models.BooleanField(db_index=True, default=False, help_text='Have we yet tried encoding a preview for this file? (ie or is it still on the queue)')),
                ('preview_tried_date', models.DateField(blank=True, help_text='When did we last try encoding a preview for this file? (Useful for if we start supporting new preview formats.)', null=True)),
                ('number', openlab.counted.models.AutoScopedNumberField(db_index=True, editable=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('path', models.FileField(help_text='Path to raw photo', upload_to=openlab.gallery.models.file_path_builder)),
                ('title', models.CharField(blank=True, help_text='Title of this photo', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A longer description, or notes about this photo', max_length=2048)),
                ('is_uploaded', models.BooleanField(default=False, help_text='Has the file successfully finished uploading?')),
                ('gallery', models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, s3uploader.models.GenericUploadableMixin),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Default photo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_photo', to='gallery.Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('number', 'gallery')]),
        ),
        migrations.AlterIndexTogether(
            name='photo',
            index_together=set([('number', 'gallery')]),
        ),
    ]
