# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medialink',
            name='gallery',
            field=models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='medialinks', to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Default photo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_photo', to='gallery.Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('number', 'gallery')]),
        ),
        migrations.AlterIndexTogether(
            name='photo',
            index_together=set([('number', 'gallery')]),
        ),
    ]
