# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 01:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import licensefield.fields
import openlab.project.fields
import openlab.release.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', licensefield.fields.LicenseField(choices=[('pd', 'Public domain'), ('cc-by', 'Creative Commons Attribution'), ('cc-by-sa', 'Creative Commons Attribution-ShareAlike'), ('gpl3', 'GPL 3.0'), ('lgpl3', 'LGPL 3.0'), ('tapr', 'TAPR Open Hardware'), ('cern', 'CERN Open Hardware')], help_text='License for this release.', max_length=24)),
                ('version', openlab.project.fields.VersionNumberField(help_text='Version number for this release.', max_length=24, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be in the form of 1.0 or 1.0.0, optionally followed by "a" (alpha), "b" (beta), or "rc1" (release candidate 1)', regex='^\\d+\\.\\d+(\\.\\d+)?(a|b|rc\\d+)?$')])),
                ('zip_path', models.FileField(blank=True, default=None, help_text='Location of zip file of all project files. Blank means it has not yet been prepared.', null=True, upload_to=openlab.release.models.file_path_builder)),
                ('components', django_extensions.db.fields.json.JSONField(default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.CharField(help_text='Describe in in 140 characters or less. (No paragraphs.)', max_length=140, verbose_name='Summary')),
                ('text', models.TextField(help_text='Project description', verbose_name='Description')),
                ('notes', models.TextField(help_text="Information about this, what's fixed, etc.", verbose_name='Release notes')),
                ('size', models.PositiveIntegerField(help_text='Size in bytes of the download')),
                ('project', models.ForeignKey(help_text='Project for this file', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='project.Project')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
