# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.PositiveSmallIntegerField(choices=[(40, 'Private'), (30, 'Direct'), (20, 'Adjacent'), (10, 'Following')], default=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('read', models.BooleanField(db_index=True, default=False, help_text='If its been read.')),
                ('mailed', models.BooleanField(db_index=True, default=False, help_text='if an email alert was sent for this notifiaction')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_generated', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': '-creation_date',
            },
        ),
    ]
