# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openlab.counted.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', openlab.counted.models.AutoScopedNumberField(db_index=True, editable=False)),
                ('olmarkdown_rendered', models.TextField(blank=True, help_text='HTML for rendered OL Markdown')),
                ('olmarkdown_summary', models.TextField(blank=True, help_text='Text-only suffix of rendered, for rendered OL Markdown')),
                ('olmarkdown_rendered_date', models.DateTimeField(blank=True, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('text', models.TextField(help_text='Message text. <em>(Markdown syntax is available.)</em>', verbose_name='Text')),
            ],
            options={
                'get_latest_by': 'creation_date',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, editable=False, help_text='Total number of items ever added')),
                ('last_edited', models.DateTimeField(auto_now=True, db_index=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_private', models.BooleanField(db_index=True, default=False, help_text='If this thread is private to subscribers.')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(help_text='Topic for the discussion thread.', max_length=255, verbose_name='Title')),
            ],
            options={
                'get_latest_by': 'last_edited',
            },
        ),
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participant', models.BooleanField(db_index=True, default=True)),
                ('is_email_subscription', models.BooleanField(db_index=True, default=True)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Thread')),
            ],
        ),
    ]
