# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_featured', models.DateTimeField(auto_now_add=True)),
                ('date_last_featured', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
