# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_featuredproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='user',
            field=models.ForeignKey(help_text='User who last updated feature (ie admin)', on_delete=django.db.models.deletion.CASCADE, related_name='featured_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
